[cerebrium.deployment]
name = "vani-cerebrium-test"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = true
include = ['./*', 'live_kit_audio.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
cpu = 2.0
memory = 8.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "cpu_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0

[cerebrium.runtime.custom]
port = 8081
dockerfile_path = "./Dockerfile"